//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class img
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string ImgPath { get; set; }
        public HttpPostedFileBase Imgfile { get; set; }
    }
}
